Poziom 1: 
Fundamenty i tworzenie tablic
Zacznijmy od podstawowych metod generowania danych i sprawdzania ich właściwości.
Zera i jedynki: 
Stwórz tablicę 2D o wymiarach 3x5 wypełnioną zerami, a następnie tablicę 1D z siedmioma jedynkami.
Sekwencje: Wygeneruj tablicę zawierającą liczby od 10 do 50, ale tylko parzyste (użyj np.arange).
Liniowy podział: Stwórz tablicę 10 liczb idealnie rozłożonych w przedziale od 0 do 5 (użyj np.linspace).
Inspekcja: Stwórz dowolną tablicę 2x3 i wypisz jej kształt (shape), liczbę wymiarów (ndim) oraz typ danych (dtype).

In [2]:
import numpy as np

mzerowa = np.zeros((3,5))
print(mzerowa)
mjedynki = np.ones((7))
print(mjedynki)

parzyste = np.arange(10,50)
parzyste = parzyste[parzyste%2==0]
print(parzyste)

liniowe = np.linspace(0,5,10)
print(liniowe)

dowolna = np.ones((2,3))
print(dowolna.shape)
print(dowolna.ndim)
print(dowolna.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1.]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
(2, 3)
2
float64


Poziom 2: Indeksowanie i Slicing
Tutaj nauczysz się "wycinać" konkretne dane z większych zbiorów.
Snajper: Stwórz macierz 4 x 4 z liczbami od 1 do 16. 
Wyciągnij z niej:Liczbę z drugiego wiersza i trzeciej kolumny.
Cały trzeci wiersz.Całą czwartą kolumnę.
Podmacierz: Z tej samej macierzy 4 x 4 wyetnij środkowy kwadrat o wymiarach 2 x 2 (elementy z wierszy 1-2 i kolumn 1-2).

In [2]:
macierz = np.arange(1,17)
macierz = macierz.reshape(4,4)
print(macierz)
print(macierz[1,2])
print(macierz[2,:])
print(macierz[:,3])

podmacierz = macierz[1:3,1:3]
print(podmacierz)




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
7
[ 9 10 11 12]
[ 4  8 12 16]
[[ 6  7]
 [10 11]]


Poziom 3: Maski logiczne i filtrowanie
To kluczowa umiejętność w analizie danych – wybieranie rekordów spełniających warunki.
Filtrowanie: Stwórz tablicę 20 losowych liczb całkowitych z zakresu 1-100 (użyj rng.integers).
Stwórz maskę dla liczb większych niż 50.
Wypisz tylko te liczby, które są większe niż 50.
Złożone warunki: Z tej samej tablicy wybierz liczby, które są jednocześnie większe niż 30 i mniejsze niż 70.

In [3]:
rng = np.array(np.random.random(20) *100,dtype=np.int16)
print(rng)
maska = rng >50
print(rng[maska])
maska = (rng >30) & (rng < 70)
print(rng[maska])




[59 88 81 60 92 57 95 96 74 58 50 58 87 49 55 82 74 57 25 28]
[59 88 81 60 92 57 95 96 74 58 58 87 55 82 74 57]
[59 60 57 58 50 58 49 55 57]


Poziom 4: Przekształcenia i statystyka
Nauczysz się zmieniać strukturę danych i wyciągać z nich wnioski.
Reshape: Stwórz tablicę 1D z 12 elementami, a następnie zmień jej kształt na 3 x 4. 
Na koniec dokonaj jej transpozycji (zamień wiersze z kolumnami).
Analiza: Wygeneruj macierz 5 x 5 z liczbami z rozkładu normalnego. 
Oblicz:Średnią i odchylenie standardowe dla całej macierzy.
Sumę wartości w każdej kolumnie osobno (axis=0).Znajdź wartość maksymalną w każdym wierszu.

In [33]:
tablica = np.arange(1,13)
tablica = tablica.reshape(3,4)
#print(tablica)
tablica = tablica.transpose()
#print(tablica)

from numpy.random import default_rng
normal_matrix = default_rng(42).normal(0,1,(5,5))
print(normal_matrix.mean())
print(normal_matrix.std())
print(normal_matrix.sum(axis=0))
print(normal_matrix.max(axis=1))

print(f"\n  {normal_matrix}")


-0.035389987592057665
0.8143009062921549
[-1.16221928 -0.44653053  0.76389804  2.77492559 -2.81482351]
[0.94056472 0.1278404  1.12724121 0.8784503  1.22254134]

  [[ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519]
 [-1.30217951  0.1278404  -0.31624259 -0.01680116 -0.85304393]
 [ 0.87939797  0.77779194  0.0660307   1.12724121  0.46750934]
 [-0.85929246  0.36875078 -0.9588826   0.8784503  -0.04992591]
 [-0.18486236 -0.68092954  1.22254134 -0.15452948 -0.42832782]]


Poziom 5: Wyzwanie praktyczne (Zadania z notatek)
Spróbuj połączyć wiedzę, by rozwiązać realne problemy opisane w Twoich materiałach.
Obsługa braków: Stwórz tablicę [10, 20, np.nan, 40, 50, np.nan]. 
Oblicz jej średnią tak, aby ignorowała wartości NaN. 
Następnie zastąp wszystkie NaN zerami.
Normalizacja: Napisz funkcję, która przyjmuje tablicę i "ściska" jej wartości do zakresu [0, 1] według wzoru z notatek: {data - min}/{max - min}

In [34]:
tablica = np.array([10, 20, np.nan, 40, 50, np.nan])
srednia = np.nanmean(tablica)
print(srednia)
print(np.nan_to_num(tablica).mean())
tablica = np.nan_to_num(tablica)

def normalizacja(df):
    x = df.min()
    y = df.max()
    return (df-x)/(y-x)

normalizacja(tablica)




30.0
20.0


array([0.2, 0.4, 0. , 0.8, 1. , 0. ])

Zadanie 1: Zaawansowany BroadcastingStwórz macierz A o wymiarach 10 x 3 wypełnioną losowymi liczbami całkowitymi z zakresu 1-10.
Stwórz wektor w o długości 3 (np. [1, 2, 3]).
Dodaj wektor w do każdego wiersza macierzy A wykorzystując broadcasting.
Stwórz wektor v o długości 10 i dodaj go do każdej kolumny macierzy A 
pamiętaj o zmianie kształtu wektora v na (10, 1), aby broadcasting zadziałał poprawnie.

In [6]:

from numpy.random import default_rng
A= default_rng(43).integers(0,10,(10,3))
print(A)
A= default_rng(43).integers(0,10,(3,10))
print(A)


[[5 6 4]
 [0 5 0]
 [2 8 4]
 [5 9 2]
 [8 7 3]
 [2 2 4]
 [6 4 1]
 [9 3 8]
 [1 2 7]
 [2 8 4]]
[[5 6 4 0 5 0 2 8 4 5]
 [9 2 8 7 3 2 2 4 6 4]
 [1 9 3 8 1 2 7 2 8 4]]


Zadanie 2: Detektyw Danych (Analiza i Czyszczenie)
Masz tablicę wyników pomiarów: pomiary = np.array([12.5, 13.2, np.nan, 11.8, 14.5, np.nan, 12.0, 50.0]).
Znajdź indeksy, na których znajdują się wartości NaN.
Oblicz sumę wszystkich poprawnych pomiarów (pomiń NaN).
Wyzwanie: Zastąp wartości NaN średnią obliczoną z pozostałych (poprawnych) elementów tej tablicy.
Usuń z tablicy tzw. "outlier" (wartość odstającą), czyli element 50.0, używając maski logicznej.

In [ ]:
pomiary = np.array([12.5, 13.2, np.nan, 11.8, 14.5, np.nan, 12.0, 50.0])

mask = np.isnan(pomiary)
print(np.where(mask == True))
suma = np.nansum(pomiary)
print(suma)
srednia = np.nanmean(pomiary)
my_pomiary = 

(array([2, 5]),)
114.0
